spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  thymeleaf:
    mode: HTML
    cache: false
  #  静态资源通行
  web:
    resources:
      static-locations: classpath:/
  datasource:
    username: root
    password: wan521ioy
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/gradem?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
server:
  port: 8080
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sun.blog.entity
#日志
logging:
  #  配置文件位置
  level:
    com.sun.blog: trace
  pattern:
    console: "%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  file:
    name: "/var/log/spring.log"

